[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#1e90ff"
backgroundColor = "#f9f9f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[general]
email = "ankit225508@gmail.com"

[theme]
base="light"
primaryColor="#4CAF50"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
headless = true
enableCORS = false
