[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#1e90ff"
backgroundColor = "#f9f9f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[general]
email = "ankitdahiya65023@gmail.com"
